apiVersion: apps/v1
kind: Deployment
metadata:
  name: indicator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indicator-api
  template:
    metadata:
      labels:
        app: indicator-api
    spec:
      containers:
        - name: indicator-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
