apiVersion: apps/v1
kind: Deployment
metadata:
  name: indicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indicator
  template:
    metadata:
      labels:
        app: indicator
    spec:
      containers:
        - name: indicator
          image: '{{ .Values.image.repository | default (printf "%s/%s" .Values.global.registry .Chart.Name) }}:{{ .Values.image.tag | default .Values.global.tag }}'
          command: ["uvicorn", "services.indicator_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-config

      nodeSelector:
        {{- toYaml (.Values.nodeSelector | default .Values.global.nodeSelector) | nindent 8 }}
