apiVersion: v2
name: trading-engine
description: Unified chart for all trading services
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: websocket-streamer
    version: 0.1.0
    repository: "file://charts/websocket-streamer"
  - name: ohlcv-api
    version: 0.1.0
    repository: "file://charts/ohlcv-api"
  - name: indicator
    version: 0.1.0
    repository: "file://charts/indicator"
