version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --maxmemory 100mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - trading-net

networks:
  trading-net:
    driver: bridge
