version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --maxmemory 100mb --maxmemory-policy allkeys-lru
    restart: always
    networks:
      - trading-net

  indicator:
    build: .
    container_name: indicator
    command: uvicorn indicator_api.indicator_service:app --host 0.0.0.0 --port 8000 --log-level info
    restart: always
    networks:
      - trading-net
    volumes:
      - ./config:/app/config
    ports:
      - "8000:8000"

  aggregator:
    build: .
    container_name: binance-aggregator
    command: python data_collection/websocket_data.py
    restart: always
    networks:
      - trading-net
    volumes:
      - ./config:/app/config

networks:
  trading-net:
    driver: bridge
