global:
  registry: registry.devops.svc.cluster.local:30000
  tag: latest
  nodeSelector:
    kubernetes.io/hostname: rpslave2 # ✅ Will be replaced dynamically via script
  image:
    repository: registry.devops.svc.cluster.local:30000
indicator:
  env:
    REDIS_HOST: redis.trading.svc.cluster.local
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 31010
ohlcv-api:
  service:
    type: NodePort
    port: 8010
    targetPort: 8010
    nodePort: 31020
websocket-streamer:
  env:
    REDIS_HOST: redis.trading.svc.cluster.local
  service:
    type: NodePort
    port: 8020
    targetPort: 8020
    nodePort: 31030
