apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-api
  template:
    metadata:
      labels:
        app: websocket-api
    spec:
      containers:
        - name: websocket-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8020
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
