image:
  tag: latest
  pullPolicy: IfNotPresent

env:
  REDIS_HOST: redis-master.trading.svc.cluster.local

nodeSelector: {}

service:
  type: NodePort
  port: 8010
  targetPort: 8010
  nodePort: 31010

autoscaling:
  enabled: false

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
