replicaCount: 1

image:
  repository: your-registry/your-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

nodeSelector:
  kubernetes.io/hostname: ""

tolerations: []

affinity: {}
