symbol: BTCUSDT
interval: 1min
use_json_logs: false
max_candles: 500

websocket:
  base_url: wss://stream.binance.com:9443
  stream_type: trade

redis:
  host: redis
  port: 6379
  db: 0
  decode_responses: true
  ohlcv_key_template: "ohlcv:{symbol}:{interval}"

binance:
  base_url: https://api.binance.com
  endpoints:
    klines: /api/v3/klines
