image:
  tag: latest
  pullPolicy: IfNotPresent

env:
  REDIS_HOST: redis-master.trading.svc.cluster.local

nodeSelector: {}

service:
  type: NodePort
  port: 8020
  targetPort: 8020
  nodePort: 31020

autoscaling:
  enabled: false

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false